### PR TITLE
Implement Range API (#315)

### PR DESCRIPTION
**Pull request by WillBAnders**
This PR implements the range API discussed in #315.

### Creation

```racket
;Upper bound
(range 10); [0, 10)
(range [10 #t]); [0, 10]

;Lower & upper bound
(range 0 10); [0, 10)
(range 0 [10 #t]); [0, 10]
(range [0 #f] [10 #t]); (0, 10]

;Using * for unbounded
(range *); [0, *)
(range 0 *); [0, *)
(range [0 #f] *); (0, *)
(range * 0); (*, 0)
(range * *); (*, *)

;Using inclusivity keywords
(range #:incl 0 10); [0, 10]
(range #:excl 0 10); (0, 10)
(range #:incl 0 #:excl 10); [0, 10)
(range #:excl 0 #:incl 10); (0, 10]
(range #:incl 0 *); [0, *) //still exclusive for unbounded
```

### API Functions

```racket
(define positive (range 1 *)); [1, *)

(range? positive); #t

(range/lower? positive); #t
(range/lower positive); 1
(range/lower-incl positive); #t

(range/upper? positive); #f
(range/upper positive); null, aka '()
(range/upper-incl positive); #f

(range/contains positive 0); #f
(range/contains positive 1); #t
(range/contains positive +inf.0); #t
(range/contains positive -inf.0); #f
```

## Implementation

The implementation is pretty straightforward. It uses a range struct which contains a lower and upper bound, which is itself a struct having a value and an inclusivity. There is also an unbounded bound which is represented by `(bound null #f)`.

### Creation

The process to create ranges is really the source of complexity here. This makes use of a macro to allow `*` to be used to define a bound as unbounded. This has three main components:

 1. Syntax classes for bound and value:
    - A bound consists of both a value and an inclusivity. It is specified as a pair as in `[value incl]`, or as only a value which will use the default inclusivity (closed-open).
    - A value is either an expression or the symbol `*` (representing unbounded).
 2. Macro for processing syntax and rewriting, in three forms:
     - Range defined with only a upper bound, which uses a lower bound of `0`.
     - Range with both lower and upper bounds
     - Range specifying values as inclusive or exclusive using keywords, as in `#:incl 1 7` or `#:excl 0 #:incl 7` (both being the same range). The use of a macro here ensures keywords are in the correct spots and prevents the issues we saw with a standard keyword function.
 3. Function for creating the range and applying defaults:
     - This simply takes the bounds extracted from the macro and applies the necessary defaults, with null values turning into unbounded bounds and null inclusivity becoming the proper default under closed-open ranges.

## TODO

From here, there are couple of core pieces which still need to be done (in a rough order):
 - [ ] Finalize the base API
 - [ ] Add iterations & sequence functions
 - [ ] Canonical ranges & domains
 - [ ] RangeSet implementation

Additionally, I would greatly appreciate some guidance on putting together documentation, tests, and contracts - I haven't worked with these before in Racket and aren't sure what the best practices are. Any other feedback on the design/implementation would be welcome too!

### CODE REVIEW

**Comment by jackfirth** [comment]
Thank you, great job taking the initiative on this. Here's my high-level feedback:

- Ranges need to work with arbitrary types using `rebellion/base/comparator`, not just numbers. Merging something that only works with numbers and trying to adapt it to arbitrary comparators later has too great a chance of introducing backwards incompatible changes. The API design must incorporate comparators from the start.

- There needs to be a publicly-exposed non-macro way of creating ranges. Otherwise it won't be possible to build functions that construct ranges without statically knowing what kind of endpoints they'll have. Use case: a webserver that builds a range from a client-provided filter string like "x <= 7". Also, attaching contracts to functions is *much* easier than attaching them to macros.

- Consider using an `option?` value (from `rebellion/base/option`) to wrap each boundary value and type , instead of encoding an absent boundary value as `null`. This is kind of mandatory if you want to support arbitrary comparators, since `null` could be a perfectly acceptable endpoint value in a range whose comparator compares lists.

- Consider adding singleton types for the boundary types instead of using booleans, like this:

```racket
(define-singleton-type exclusive-bound)
(define-singleton-type inclusive-bound)

;; then, in some code inspecting the type of bound:

(define type (range-lower-bound-type rng))
(cond
  [(exclusive-bound? type) ...]
  [(inclusive-bound? type) ...])
```

- It's tricky for me to skim the API of the module. That can be solved by adding contracts. Here's what I recommend doing at the top of the module:

```racket
#lang racket/base

;; The provide form should go as close to the top of the module as it can,
;; in order to give a high-level summary of the module. We only require
;; racket/contract/base here because it provides contract-out, and the provide
;; macro won't compile if it uses provide transformers (like contract-out, rename-out,
;; etc.) that haven't been imported yet. All other dependencies we require *after*
;; the provide form.
(require racket/contract/base)

(provide
 (contract-out
  [range? predicate/c]
  [range/contains (-> range? any/c boolean?)]
  ...))

;; This is where we require everything the module actually needs
(require ...)

... module body ...
```

**Comment by WillBAnders** [comment]
I've addressed the following points above:
 - [X] Comparators are now supported via `rebellion/base/comparator`. The default is `real<=>`.
 - [X] `range/create` is now exposed in the API. Unsure if the default values with `null` should also be exposed or left internal. The semantics of it are already part of the API through the macro, so it's not like it's implementation behavior either.
 - [X] `option` is used for bound values now. I've also removed the inner `bound` struct for simplicity as I never intended on exposing that to the API anyways.
 - [ ] Using singleton types for inclusive/exclusive will only complicate things. The end result is always `#t/#f` and its easiest to work with that for everything.
 - [X] Contracts for functions are done. I have no idea how to contract the macro, so yeah xD

I'll probably let this sit for a week or two until I'm more free and then I'll start looking into either the sequence things or the domain piece.

**Comment by jackfirth** [comment]
I just wrote up #373, which is another attempt at implementing a range API. I've also invited you to be a contributor of Rebellion.

The main difference between that pull request and this one is that one abandons the macro for creating ranges. The keyword-based macro approach doesn't sit right with me because whenever I see keywords used for something in Racket that looks like a function call, I assume that their position doesn't matter. Instead, the API in #373 provides a data type for a range bound that can be either `(inclusive-bound x)`, `(exclusive-bound x)`, or `unbounded`. To keep the simple cases easy to write, it provides convenience constructors like `(closed-range x y)`, `(closed-open-range x y)`, and `(at-most x)`. Let me know what you think!

**Comment by jackfirth** [comment]
Closing this since the range API merged in #373 is mostly stable now.

**Pull request closed without merging**
